/**
 * WASMLoader - WebAssembly Module Loader with Caching and Fallback
 *
 * Provides high-performance WASM module loading for WebOS with:
 * - Automatic caching of loaded modules
 * - Feature detection for WASM support
 * - Graceful fallback to JavaScript implementations
 * - Worker pool integration for background processing
 */

export class WASMLoader {
    constructor() {
        this.cache = new Map();
        this.wasmSupported = this.detectWASMSupport();
        this.loading = new Map(); // Track in-progress loads
    }

    /**
     * Detect if WebAssembly is supported in this browser
     */
    detectWASMSupport() {
        try {
            if (typeof WebAssembly === 'object' &&
                typeof WebAssembly.instantiate === 'function') {
                // Test with a minimal WASM module
                const module = new WebAssembly.Module(
                    new Uint8Array([0x00, 0x61, 0x73, 0x6d, 0x01, 0x00, 0x00, 0x00])
                );
                return module instanceof WebAssembly.Module;
            }
            return false;
        } catch (e) {
            console.warn('WebAssembly not supported:', e);
            return false;
        }
    }

    /**
     * Load a WASM module with caching
     * @param {string} moduleName - Name of the module (compression, crypto, text-processing)
     * @param {Object} fallback - Optional fallback JavaScript implementation
     * @returns {Promise<Object>} The loaded module
     */
    async loadModule(moduleName, fallback = null) {
        // Check cache first
        if (this.cache.has(moduleName)) {
            return this.cache.get(moduleName);
        }

        // Check if already loading (prevent duplicate loads)
        if (this.loading.has(moduleName)) {
            return this.loading.get(moduleName);
        }

        // If WASM not supported, use fallback
        if (!this.wasmSupported) {
            console.warn(`WASM not supported, using JavaScript fallback for ${moduleName}`);
            if (fallback) {
                this.cache.set(moduleName, fallback);
                return fallback;
            }
            throw new Error(`WASM not supported and no fallback provided for ${moduleName}`);
        }

        // Start loading
        const loadPromise = this._loadWASMModule(moduleName, fallback);
        this.loading.set(moduleName, loadPromise);

        try {
            const module = await loadPromise;
            this.cache.set(moduleName, module);
            return module;
        } catch (error) {
            console.error(`Failed to load WASM module ${moduleName}:`, error);

            // Try fallback on error
            if (fallback) {
                console.warn(`Using JavaScript fallback for ${moduleName} due to load error`);
                this.cache.set(moduleName, fallback);
                return fallback;
            }
            throw error;
        } finally {
            this.loading.delete(moduleName);
        }
    }

    /**
     * Internal method to load WASM module
     * @private
     */
    async _loadWASMModule(moduleName, fallback) {
        try {
            // Import the WASM module generated by wasm-pack
            const module = await import(`/wasm/${moduleName}/${moduleName.replace(/-/g, '_')}.js`);

            // Initialize the WASM module
            await module.default();

            // Return the module exports
            return module;
        } catch (error) {
            console.error(`Error loading WASM module ${moduleName}:`, error);

            // If we have a fallback, don't throw yet
            if (fallback) {
                return fallback;
            }
            throw error;
        }
    }

    /**
     * Preload modules in the background
     * @param {string[]} moduleNames - Array of module names to preload
     */
    async preloadModules(moduleNames) {
        const promises = moduleNames.map(name =>
            this.loadModule(name).catch(err => {
                console.warn(`Failed to preload ${name}:`, err);
                return null;
            })
        );
        await Promise.all(promises);
    }

    /**
     * Clear the cache for a specific module or all modules
     * @param {string} moduleName - Optional module name to clear
     */
    clearCache(moduleName = null) {
        if (moduleName) {
            this.cache.delete(moduleName);
        } else {
            this.cache.clear();
        }
    }

    /**
     * Get cache statistics
     */
    getCacheStats() {
        return {
            size: this.cache.size,
            modules: Array.from(this.cache.keys()),
            wasmSupported: this.wasmSupported,
            loading: Array.from(this.loading.keys())
        };
    }

    /**
     * Check if a module is loaded
     * @param {string} moduleName
     */
    isLoaded(moduleName) {
        return this.cache.has(moduleName);
    }

    /**
     * Check if a module is currently loading
     * @param {string} moduleName
     */
    isLoading(moduleName) {
        return this.loading.has(moduleName);
    }
}

// Create and export singleton instance
export const wasmLoader = new WASMLoader();

// Export default
export default wasmLoader;
